name: flutter_amplify_auth_sampler
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  amplify_auth_cognito:
  amplify_authenticator:
  amplify_flutter:
  flutter:
    sdk: flutter
  flutter_riverpod:
  go_router:
  riverpod:
  riverpod_annotation:

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_test:
    sdk: flutter
  pedantic_mono:
  riverpod_generator:
  riverpod_lint:

flutter:
  uses-material-design: true
